using System.Runtime.InteropServices;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Constant {
	public static string isFirst = "isFirst";
	public static string isReview = "isReview";
	public static string isKeyUsed = "isKeyUsed";
	public static string playerLevel = "playerLevel";
	public static string playerExp = "playerExp";
	public static string playerKey = "playerKey";
	public static string[] playerItem = { "playerItem0", "playerItem1", "playerItem2", "playerItem3", "playerItem4" };
	public static string UseSpeak = "UseSpeak";
	public static string LastPackage = "LastPackage";
	public static string LastStage = "LastStage";
	public static string LastStageIndex = "LastStageIndex";
	public static string LastKeyTime = "LastKeyTime";
	public static string PackageLimit = "PackageLimit";
	public static string[] StageLimit = {"StageLimitKeyboard", "StageLimitSpeak"};
	public static string BGM = "BGM";
	public static string SE = "SE";
	public static string RemoveAd = "RemoveAd";
	public static string CanRemoveAd = "CanRemoveAd";
	public static string SavingMode = "SavingMode";
	public static string Package = "Package";

	public static string PlayInfo = "PlayInfo";
	public static string MainScene = "MainScene";
	public static string StageScene = "StageScene";
	public static string GameScene = "GameScene";
	public static string ShopScene = "ShopScene";
	public static string HelpScene = "HelpScene";
	public static string MiddleScene = "MiddleScene";
	public static string PracticeScene = "PracticeScene";
	public static string GameManager = "GameManager";
	public static string PracticeManager = "PracticeManager";

	#if UNITY_ANDROID
	public static string AndroidPackage = "com.familsoft.defenseword.";
	public static string ReviewURL = "market://details?id=com.familsoft.catchword";
	#elif UNITY_IOS
	public static string ReviewURL = "itms-apps://itunes.apple.com/app/id1267684552";
	#endif

	public static string _blurSizeXY = "_blurSizeXY";

	public static string StringMainHelpRemoveAd;
	public static string StringMainHelpSavingMode;
	public static string StringMainHelpAboutGame;
	public static string StringMainHelpAboutItem;
	public static string StringMainQuitMessage;
	public static string StringQuitMessage;
	public static string StringQuitConfirm;
	public static string StringPanelCancel;
	public static string StringNoKeyMessage;
	public static string StringNoKeyConfirm;
	public static string StringGameReady;
	public static string StringGameStart;
	public static string StringGameResultEarnedExp;
	public static string StringGameResultEarnedItem;
	public static string StringGameResultNeedItem;
	public static string StringGameReviewMessage;
	public static string StringGameReviewConfirm;
	public static string[] StringShopItemButtonTitle = new string[9];
	public static string[] StringShopPackageButtonTitle = new string[2];
	public static string StringShopItemButton1Money;
	public static string StringShopItemButton8Explain;
	public static string StringShopButtonPurchased;
	public static string StringShopCatMessage;
	public static string[] StringHelpGameTutorial = new string[12];
	public static string[] StringHelpItemTutorial = new string[7];
	public static string StringHelpPlayerBar;
	public static string StringHelpWord;
	public static string StringHelpInputBar;
	public static string StringHelpTargetWord;
	public static string StringHelpCatchedWord;
	public static string StringHelpTyping;
	public static string StringHelpRandomItemWord;
	public static string StringHelpRemainTime;
	public static string StringHelpSpeechButton;
	public static string StringHelpSpeechVolume;
	public static string StringHelpTypedWord;
	public static string StringHelpRemoverItem;
	public static string StringHelpWordToDisappear;
	public static string StringHelpRainItem;
	public static string StringHelpWordsToDisappear;
	public static string StringHelpSandglassItem;
	public static string StringHelpHPBar;
	public static string StringHelpRecoverItem;
	public static string StringHelpBombPreventerItem;
	public static string StringHelpForiOS;


	public static List<Package> packages = new List<Package> () {
		new Package (0, new string[] {
			"account",
			"address",
			"afford",
			"apple",
			"application",
			"apply",
			"approach",
			"attribute",
			"because",
			"become",
			"before",
			"benefit",
			"blame",
			"both",
			"bother",
			"break",
			"bring",
			"blow",
			"commit",
			"complete",
			"conduct",
			"consider",
			"contact",
			"describe",
			"despite",
			"determine",
			"direct",
			"discuss",
			"due",
			"establish",
			"estimate",
			"expect",
			"experience",
			"extend",
			"expand",
			"exceed",
			"facility",
			"fall",
			"favor",
			"find",
			"follow",
			"function",
			"get",
			"give",
			"good",
			"grant",
			"hang",
			"hard",
			"have",
			"hear",
			"help",
			"hold",
			"hope",
			"hurt",
			"improve",
			"increase",
			"indicate",
			"interest",
			"join",
			"judge",
			"junior",
			"just",
			"justice",
			"justify",
			"keen",
			"keep",
			"kindly",
			"lack",
			"late",
			"level",
			"lose",
			"maintain",
			"make",
			"matter",
			"mention",
			"modify",
			"obtain",
			"offer",
			"once",
			"operation",
			"opportunity",
			"order",
			"otherwise",
			"potential",
			"practice",
			"prefer",
			"prevent",
			"proceed",
			"progress",
			"promote",
			"provide",
			"qualification",
			"quality",
			"quantity",
			"question",
			"quiet",
			"quit",
			"quite",
			"quotation",
			"refer",
			"regard",
			"remain",
			"request",
			"require",
			"respect",
			"rise",
			"since",
			"state",
			"stuff",
			"subject",
			"submit",
			"suggest",
			"support",
			"take",
			"then",
			"transfer",
			"transition",
			"travel",
			"treat",
			"undertake",
			"unique",
			"unless",
			"until",
			"upon",
			"upset",
			"utility",
			"value",
			"view",
			"visit",
			"which",
			"while",
			"wonder",
			"work",
			"would",
			"write",
			"yarn",
			"year",
			"yell",
			"yet",
			"you",
			"your",
			"youth",
			"need",
			"note",
			"notice",
			"notify",
			"nothing",
			"zebra",
			"zero",
			"zone",
			"zoom",
			"culture",
			"vice",
			"envy",
			"passion",
			"individual",
			"emotion",
			"evolution",
			"system",
			"challenge",
			"luxury",
			"conquest",
			"panic",
			"influence",
			"compromise",
			"comfort",
			"candidate",
			"destiny",
			"property",
			"decrease",
			"principle",
			"victory",
			"purpose",
			"fantasy",
			"access",
			"mercy",
			"logic",
			"commerce",
			"legend",
			"tension",
			"credit",
			"survive",
			"relate",
			"isolate",
			"main",
			"remote",
			"native",
			"focus",
			"adult",
			"token",
			"risk",
			"staff",
			"tidy",
			"huge",
			"shy",
			"rapid",
			"local",
			"promise",
			"part",
			"ready",
			//200
			"apreciate",
			"appropriate",
			"assume",
			"available",
			"area",
			"besides",
			"build",
			"certain",
			"charge",
			"concern",
			"confirm",
			"character",
			"community",
			"demonstrate",
			"develop",
			"discipline",
			"draw",
			"effect",
			"encourage",
			"ensure",
			"executive",
			"facilitate",
			"feature",
			"figure",
			"further",
			"adore",
			"adopt",
			"gather",
			"general",
			"generate",
			"guarantee",
			"grow",
			"gratitude",
			"happen",
			"hesitate",
			"identify",
			"implement",
			"influence",
			"involve",
			"issue",
			"jealous",
			"kindergarten",
			"knock",
			"know",
			"learn",
			"likely",
			"listen",
			"maintenance",
			"manage",
			"mandatory",
			"material",
			"measure",
			"observe",
			"occur",
			"organization",
			"perspective",
			"provision",
			"qualify",
			"quote",
			"recognize",
			"reference",
			"relevant",
			"secure",
			"specific",
			"usually",
			"usage",
			"valid",
			"variation",
			"various",
			"vehicle",
			"verify",
			"withdraw",
			"within",
			"yawn",
			"yield",
			"nature",
			"neither",
			"nervous",
			"zeal",
			"zealous",
			"tradition",
			"religion",
			"civilization",
			"instinct",
			"fatigue",
			"method",
			"psychology",
			"sacrifice",
			"species",
			"moisture",
			"environment",
			"theory",
			"struggle",
			"dignity",
			"genius",
			"significance",
			"transparent",
			"ceremony",
			"sigh",
			//99
			"bulb",
			"commitment",
			"data",
			"either",
			"brief",
			"abbreviate",
			"adjourn",
			"adjust",
			"acquire",
			"genuine",
			"initiative",
			"journal",
			"journey",
			"jurisdiction",
			"kneel",
			"knowledge",
			"known",
			"lead",
			"leave",
			"literature",
			"significant",
			"sponsor",
			"session",
			"though",
			"thought",
			"through",
			"thus",
			"undergo",
			"urge",
			"vulnerable",
			"versatile",
			"whereas",
			"xylophone",
			"xenophobia",
			"necessary",
			"neglect",
			"nevertheless",
			"zenith",
			"patriotism",
			"literature",
			"sympathy",
			"melancholy",
			"trial",
			"intelligence"
			//44
		}, 27,
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to200, 100, 10f, 0, 10f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to200, 100, 20f, 0, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to200, 90, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to200, 90, 35f, 0.3f, 3f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to200, 90, 40f, 0.2f, 2.5f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to200, 100, 30f, 0.2f, 3f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to299, 90, 35f, 0.3f, 3f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to299, 100, 40f, 0.2f, 2.5f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to299, 80, 40f, 0.3f, 2.5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 100, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 90, 30f, 0.3f, 3f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 80, 40f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 100, 30f, 0.2f, 4f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 90, 35f, 0.3f, 3f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to299, 80, 30f, 0.1f, 3f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 90, 30f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 80, 35f, 0.3f, 2.5f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 70, 40f, 0.3f, 4f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 90, 35f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 100, 30f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 80, 35f, 0.3f, 5f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 70, 35f, 0.2f, 4.5f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 60, 40f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 50, 40f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 40, 45f, 0.1f, 3.5f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 30, 45f, 0.1f, 3f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 30, 50f, 0.1f, 2.5f)
		),
		new Package (1, new string[]{
				"standard",
				"handsome",
				"student",
				"activity",
				"admiral",
				"advantage",
				"amount",
				"angel",
				"background",
				"balance",
				"base",
				"bat",
				"beast",
				"beauty",
				"bike",
				"birth",
				"blanket",
				"bottom",
				"branch",
				"cage",
				"candle",
				"cash",
				"chain",
				"climate",
				"competition",
				"concert",
				"conversation",
				"copy",
				"crash",
				"crime",
				"degree",
				"delight",
				"design",
				"desire",
				"dialog",
				"diary",
				"drum",
				"duck",
				"electricity",
				"elementary",
				"enemy",
				"exit",
				"express",
				"fence",
				"flood",
				"force",
				"foundation",
				"funeral",
				"handle",
				"import",
				"information",
				"insect",
				"joke",
				"ladder",
				"lady",
				"lake",
				"license",
				"limit",
				"lock",
				"log",
				"magazine",
				"mankind",
				"marriage",
				"member",
				"nickname",
				"object",
				"office",
				"phone",
				"poet",
				"pollution",
				"population",
				"port",
				"position",
				"problem",
				"pronunciation",
				"pulse",
				"pumpkin",
				"purse",
				"robber",
				"ruin",
				"sample",
				"sand",
				"saw",
				"scar",
				"schedule",
				"scholar",
				"score",
				"shock",
				"shower",
				"sight",
				"silk",
				"site",
				"situation",
				"slave",
				"snake",
				"solution",
				"spade",
				"spirit",
				"spot",
				"square",
				"stadium",
				"stage",
				"stair",
				"stream",
				"stress",
				"stripe",
				"supply",
				"tax",
				"tea",
				"tent",
				"tern",
				"theater",
				"tool",
				"tooth",
				"top",
				"treasure",
				"trick",
				"type",
				"universe",
				"vase",
				"wedding",
				"absent",
				"amazing",
				"careful",
				"cloudy",
				"crowded",
				"cruel",
				"curious",
				"dangerous",
				"different",
				"empty",
				"excited",
				"grand",
				"grave",
				"gray",
				"great",
				"green",
				"indoor",
				"interested",
				"international",
				"loose",
				"low",
				"national",
				"noble",
				"other",
				"peaceful",
				"polite",
				"rainy",
				"real",
				"sharp",
				"silly",
				"smart",
				"solar",
				"steady",
				"straight",
				"stupid",
				"unlike",
				"useless",
				"amuse",
				"delight",
				"deliver",
				"deserve",
				"disappear",
				"drive",
				"drum",
				"include",
				"insist",
				"locate",
				"nod",
				"overhear",
				"powder",
				"pray",
				"press",
				"produce",
				"protect",
				"scare",
				"sink",
				"slide",
				"itself",
				"myself",
				"recently",
				"slowly",
				"education",
				"unity",
				"habit",
				"opinion",
				"surface",
				"project",
				"senior",
				"edge",
				"biology",
				"contest",
				"semester",
				"passenger",
				"marble",
				"invader",
				"castle",
				"desert",
				"event",
				"basement",
				//200
				"bottle",
				"burden",
				"courage",
				"course",
				"damage",
				"error",
				"fault",
				"feather",
				"gesture",
				"ghost",
				"government",
				"grace",
				"guest",
				"hunger",
				"jewel",
				"label",
				"lamb",
				"medicine",
				"merchant",
				"mystery",
				"nail",
				"neighbor",
				"palace",
				"parade",
				"pressure",
				"quarter",
				"quiz",
				"relay",
				"republic",
				"resource",
				"riddle",
				"secretary",
				"seed",
				"series",
				"shade",
				"sheep",
				"stomach",
				"thumb",
				"tongue",
				"vegetable",
				"voyage",
				"wealth",
				"whole",
				"worth",
				"anxious",
				"extreme",
				"fair",
				"flat",
				"religious",
				"serious",
				"valuable",
				"abuse",
				"alarm",
				"beat",
				"bend",
				"bet",
				"breathe",
				"bury",
				"celebrate",
				"compare",
				"complain",
				"create",
				"cure",
				"declare",
				"engage",
				"explore",
				"force",
				"gain",
				"prove",
				"puzzle",
				"replace",
				"return",
				"review",
				"rid",
				"roar",
				"scream",
				"search",
				"serve",
				"settle",
				"spread",
				"stare",
				"surround",
				"tear",
				"vote",
				"wake",
				"abroad",
				"ahead",
				"exactly",
				"immediately",
				"revloution",
				"glory",
				"section",
				"ancestor",
				"relative",
				"superstition",
				"appetite",
				"statue",
				"furniture",
				"language",
				//99
				"board",
				"bone",
				"chalk",
				"cheer",
				"column",
				"envelope",
				"garage",
				"heart",
				"hollow",
				"horizon",
				"leaf",
				"liberty",
				"oath",
				"praise",
				"thermometer",
				"thief",
				"precious",
				"associate",
				"guard",
				"slip",
				"smell",
				"wrap",
				"apart",
				"symbol",
				"sculpture",
				"instrument",
				"debt",
				"hydrogen",
				"sophomore",
				"pilgrim",
				"athlete",
				"mammal",
				"inning",
				"cemetery",
				"torch",
				"composer",
				"atom",
				"petal",
				"throat",
				"valley",
				"amateur",
				"laundry",
				"lantern",
				"astonish"
				//44
		}, 27,
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to200, 100, 30f, 0.1f, 5f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to200, 100, 40f, 0, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to200, 100, 30f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to200, 100, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to200, 100, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to200, 95, 35f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 100, 30f, 0.2f, 4f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to299, 90, 35f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 100, 30f, 0.2f, 3f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to299, 90, 30f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 100, 30f, 0.3f, 4f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to299, 90, 35f, 0.2f, 4f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to299, 90, 40f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 100, 30f, 0.3f, 3f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to299, 95, 35f, 0.2f, 4f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to343, 100, 40f, 0.1f, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to343, 100, 35f, 0.2f, 4f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to343, 100, 40f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to343, 100, 50f, 0, 3f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to343, 100, 40f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 90, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 90, 35f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to343, 100, 30f, 0.2f, 4f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 90, 35f, 0.1f, 5f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 90, 40f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 90, 40f, 0.1f, 3f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 90, 30f, 0.2f, 5f)
		),
		new Package (2, new string[] {
				"statement",
				"invent",
				"train",
				"intelligent",
				"barbarian",
				"holiday",
				"vacation",
				"avoid",
				"weekend",
				"share",
				"appointment",
				"appoint",
				"pork",
				"beef",
				"strict",
				"against",
				"alcoholic",
				"proper",
				"weapon",
				"handshake",
				"peace",
				"manner",
				"harm",
				"honor",
				"origin",
				"original",
				"originate",
				"custom",
				"prudent",
				"rival",
				"gradually",
				"antique",
				"baggage",
				"luggage",
				"swim",
				"deal",
				"tube",
				"bath",
				"poison",
				"awful",
				"wax",
				"weed",
				"even",
				"infant",
				"immortal",
				"territory",
				"safe",
				"bite",
				"lean",
				"appear",
				"appearance",
				"overweight",
				"underweight",
				"cope",
				"aggressive",
				"science",
				"stimulate",
				"stimulation",
				"advance",
				"mission",
				"instead",
				"nobility",
				"responsible",
				"safety",
				"official",
				"digest",
				"fry",
				"relax",
				"dull",
				"frequent",
				"frequently",
				"instructor",
				"chew",
				"jaw",
				"muscle",
				"alert",
				"consideration",
				"circulation",
				"fresh",
				"flash",
				"comfortable",
				"pride",
				"ball",
				"clue",
				"ability",
				"capable",
				"suspect",
				"suspicion",
				"impatient",
				"fold",
				"chest",
				"patient",
				"patience",
				"posture",
				"dread",
				"probably",
				"interact",
				"interactive",
				"attitude",
				"actually",
				"demand",
				"factory",
				"reflect",
				"reflection",
				"mechanic",
				"graduate",
				"graduation",
				"spider",
				"innate",
				"salmon",
				"current",
				"override",
				"institution",
				"nurse",
				"recover",
				"recovery",
				"term",
				"ordinary",
				"volcano",
				"century",
				"ancient",
				"touch",
				"transform",
				"reduce",
				"array",
				"behavior",
				"reward",
				"bride",
				"identical",
				"external",
				"internal",
				"satisfy",
				"spell",
				"spelling",
				"mercury",
				"plunge",
				"freeze",
				"forecast",
				"predict",
				"debate",
				"cause",
				"brisk",
				"glance",
				"graceful",
				"resist",
				"gorilla",
				"creature",
				"creator",
				"ultimate",
				"starve",
				"starvation",
				"lawyer",
				"attorney",
				"unexpected",
				"realistic",
				"evident",
				"fit",
				"accept",
				"forward",
				"free",
				"past",
				"textbook",
				"appeal",
				"military",
				"nuclear",
				"slow",
				"treatment",
				"injury",
				"victim",
				"concept",
				"update",
				"translate",
				"obey",
				"waste",
				"attention",
				"act",
				"swing",
				"lamp",
				"transport",
				"teenager",
				"aircraft",
				"uniform",
				"relationship",
				"consumer",
				"forest",
				"surprise",
				"tropical",
				"production",
				"remind",
				"offense",
				"confidence",
				"cheap",
				"puppy",
				"protection",
				"magic",
				"immunity",
				"separate",
				"entire",
				"exist",
				"average",
				//200
				"society",
				"social",
				"suppress",
				"legal",
				"illegal",
				"universal",
				"endowment",
				"superior",
				"inferior",
				"familiarize",
				"prohibition",
				"prohibit",
				"beverage",
				"antiquity",
				"variable",
				"raise",
				"obvious",
				"obviously",
				"applaud",
				"applause",
				"achievement",
				"throw",
				"etiquette",
				"chief",
				"accomplish",
				"substitute",
				"labor",
				"technique",
				"conviction",
				"convince",
				"capability",
				"field",
				"philosophy",
				"balloon",
				"massive",
				"copyright",
				"upgrade",
				"curiosity",
				"sensitive",
				"hunting",
				"performance",
				"perform",
				"laboratory",
				"sociologist",
				"contextual",
				"investment",
				"marketplace",
				"clearance",
				"physical",
				"mental",
				"linguistic",
				"helpful",
				"impressive",
				"dramatic",
				"enroll",
				"effective",
				"certainly",
				"technology",
				"suggestion",
				"profound",
				"secondary",
				"chemistry",
				"objective",
				"million",
				"billion",
				"medium",
				"rank",
				"influential",
				"accompany",
				"rainfall",
				"distribute",
				"distribution",
				"clay",
				"arrangement",
				"gravity",
				"direction",
				"coincide",
				"dormitory",
				"marry",
				"organism",
				"maker",
				"mount",
				"prize",
				"parrot",
				"recycle",
				"insurance",
				"particular",
				"ignorant",
				"ignorance",
				"patrol",
				"warn",
				"immensity",
				"thread",
				"conclude",
				"rush",
				"fearful",
				"reject",
				"enter",
				"captain",
				//99
				"inheritance",
				"reinforce",
				"region",
				"acquaint",
				"convey",
				"survival",
				"volunteer",
				"exaggerate",
				"eager",
				"equality",
				"accurate",
				"manufacture",
				"resemblance",
				"refrigerator",
				"advertisement",
				"suitable",
				"canal",
				"consequently",
				"geometric",
				"chronic",
				"shore",
				"entrance",
				"deny",
				"denial",
				"surgery",
				"funny",
				"useful",
				"conflict",
				"career",
				"replacement",
				"cliff",
				"decade",
				"geography",
				"financial",
				"stretch",
				"emphatically",
				"premature",
				"audience",
				"shortage",
				"elaborate",
				"hurry",
				"distinction",
				"distinguish",
				"complex"
				//44
			}, 27,
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to299, 100, 35f, 0.1f, 5f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to299, 100, 40f, 0, 5f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to343, 90, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to299, 100, 30f, 0.1f, 5f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to299, 100, 40f, 0, 4f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to343, 100, 35f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to299, 100, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to299, 100, 40f, 0, 3f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 90, 30f, 0.1f, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to299, 100, 30f, 0.2f, 4f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to299, 100, 45f, 0, 5f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 95, 35f, 0.1f, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to299, 100, 30f, 0.3f, 5f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to299, 100, 45f, 0, 4f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 95, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to299, 100, 30f, 0.3f, 4f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to299, 100, 45f, 0, 3f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 90, 35f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to299, 100, 35f, 0.1f, 5f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to299, 95, 50f, 0, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to343, 100, 35f, 0.2f, 4f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to299, 100, 35f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to299, 90, 50f, 0, 4f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to343, 90, 30f, 0.2f, 4f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to343, 90, 35f, 0.2f, 4f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to343, 90, 40f, 0.2f, 4f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 90, 35f, 0.3f, 4f)
		),
		new Package(3, new string[] {
			"Nagasaki",
			"Beppu",
			"Wuchang",
			"Miyazaki",
			"Yaunde",
			"sanaa",
			"Wenzhou",
			"Yanan",
			"Esfahan",
			"Iquique",
			"Gunma",
			"Harbin",
			"Bunol",
			"Jiangsu",
			"Dunhua",
			"Kagoshima",
			"Shenzhen",
			"Durban",
			"Ecouen",
			"Minsk",
			"Bayreuth",
			"Patras",
			"Riquewihr",
			"Pierre",
			"Kyoto",
			"Yichang",
			"Baotou",
			"Ashkhabad",
			"Guangzhou",
			"Tallinn",
			"Hakodate",
			"Dijon",
			"Melk",
			"Krakow",
			"Damascus",
			"Luxor",
			"Worms",
			"Davos",
			"Napier",
			"Heho",
			"Hazelton",
			"Compiegne",
			"Wuxi",
			"Taupo",
			"Hunan",
			"Dodoma",
			"Aomori",
			"Juneau",
			"Nanyang",
			"Handan",
			"Bolton",
			"Nara",
			"Kobe",
			"Nantou",
			"Tours",
			"Seto",
			"Naruto",
			"Turfan",
			"Metz",
			"Breda",
			"Burnley",
			"Toyama",
			"Osaka",
			"Manaus",
			"Kamakura",
			"Toulon",
			"Sigulda",
			"Perpignan",
			"Halle",
			"Trondheim",
			"Brno",
			"Kusiro",
			"Palikir",
			"Hefei",
			"Blackburn",
			"Gard",
			"Cuzco",
			"Malmo",
			"Nanaimo",
			"Dujiangyan",
			"Takamatsu",
			"Sibiu",
			"Avila",
			"Nurnberg",
			"Yamaguchi",
			"Naumburg",
			"Thimphu",
			"Edmonton",
			"Calabar",
			"Helong",
			"Chengde",
			"Khania",
			"Chiba",
			"Lanzhou",
			"Aachen",
			"Yamato",
			"Tainan",
			"Kaifeng",
			"Qufu",
			"Bremen",
			"Yerevan",
			"Jiaxing",
			"Salzburg",
			"Frankfort",
			"Luoyang",
			"Odense",
			"Porto",
			"stavanger",
			"Meissen",
			"Beograd",
			"Hokkaido",
			"Panajachel",
			"Barbizon",
			"Nikko",
			"Eisenach",
			"Sukhothai",
			"Mbombela",
			"Otaru",
			"Polokwane",
			"Puebla",
			"Erfurt",
			"Basrah",
			"Chartres",
			"Funafuti",
			"Hiroshima",
			"Neimenggu",
			"Okayama",
			"Fukuyama",
			"Bergen",
			"Quanzhou",
			"Changzhou",
			"Rizhao",
			"Zibo",
			"Brisbane",
			"Augsburg",
			"Kunming",
			"Fussen",
			"Vila",
			"Shanxi",
			"Luzern",
			"Changsha",
			"Nanchang",
			"Milano",
			"Jingdezhen",
			"Abashiri",
			"Nagoya",
			"Dunhuang",
			"Koblenz",
			"Yantai",
			"Hubei",
			"Hannover",
			"Kochi",
			"Sunderland",
			"Rotorua",
			"Lusaka",
			"Assisi",
			"Hakuba",
			"Pamplona",
			"Kurashiki",
			"Niigata",
			"Guanajuato",
			"Wuerzburg",
			"Podgorica",
			"Constanta",
			"Anaheim",
			"Menton",
			"Shaanxi",
			"Yokohama",
			"Porto-Novo",
			"Jiayuguan",
			"Qiqihar",
			"Praia",
			"Tirana",
			"Shizuoka",
			"Hunchun",
			"Toulouse",
			"Weihai",
			"Zhongshan",
			"Oranjestad",
			"Mthatha",
			"Haikou",
			"Jilin",
			"Pattaya",
			"Nagano",
			"Hulunbuir",
			"Antalya",
			"Oradea",
			"Guizhou",
			"Sevilla",
			"Salamanca",
			"Krabi",
			"Banaue",
			"Jiangxi",
			"Harare",
			"Ljubljana",
			"Longjing",
			"Teheran",
			"Torino",
			"Etretat",
			"Auckland",
			"Honiara",
			"Guiyang",
			"Foix",
			"Chibi",
			"Nanning",
			"Nazca",
			"Alkmaar",
			"Ningxia",
			"Liaoning",
			"Kaohsiung",
			"Perth",
			"Tongling",
			"Moskva",
			"Skopje",
			"Pyrenees",
			"Mulhouse",
			"Utulei",
			"Xuchang",
			"Anhui",
			"Wenchuan",
			"Marseille",
			"Trenton",
			"Oaxaca",
			"Elsinore",
			"Chantilly",
			"Bamberg",
			"Furano",
			"Arica",
			"Jilin",
			"Sicilia",
			"Calama",
			"Shenyang",
			"Kandahar",
			"Siwa",
			"Jiamusi",
			"Hartford",
			"Lille",
			"Hebei",
			"Yunnan",
			"Fukuoka",
			"Hohhot",
			"Okinawa",
			"Fuzhou",
			"Almaty",
			"Jingzhou",
			"Guilin",
			"Boise",
			"Shaoxing",
			"Hualian",
			"Sichuan",
			"Xuzhou",
			"Sanya",
			"Majuro",
			"Nerchinsk",
			"Lilongwe",
			"Ordos",
			"Yogjakarta",
			"Foshan",
			"Xi'an",
			"Hakone",
			"Cesis",
			"Guangxi",
			"Luxembourg",
			"Nelspruit",
			"Xochimilco",
			"Teotihuacan",
			"Carcassonne",
			"Tangshan",
			"Palermo",
			"Gothenburg",
			"Naypyidaw",
			"Besancon",
			"Irkutsk",
			"Yueyang",
			"Rudesheim",
			"Jiangyin",
			"Sintra",
			"Zhangjiajie",
			"Nanjing",
			"Stuttgart",
			"Dortmund",
			"Jiuzhaigou",
			"Taizhong",
			"Jiaozhou",
			"Mainz",
			"Chengdu",
			"Montpelier",
			"Tarawa",
			"Kingstown",
			"Valleta",
			"Dongguan",
			"Melekeok",
			"Warszawa",
			"Ningbo",
			"Eindhoven",
			"Groningen",
			"Xining",
			"Sighisoara",
			"Fallujah",
			"Apennines",
			"Fujian",
			"Fukushima",
			"Qinghai",
			"Ramallah",
			"Guangdong",
			"Ayutthaya",
			"Sapporo",
			"Taiyuan",
			"Castries",
			"Shimonoseki",
			"Rocamadour",
			"Rustenburg",
			"Bloemfontein",
			"Qinhuangdao",
			"Noboribetsu",
			"Valparaiso",
			"Basseterre",
			"Luxembourg",
			"Christchurch",
			"Cuernavaca",
			"Novosibirsk",
			"Guadalajara",
			"Lillehammer",
			"Ulaanbaatar",
			"Cluj-Napoca",
			"Jinggangshan",
			"Andorra-la-Vella",
			"Wolverhampton",
			"Montpellier",
			"Saint-Denis",
			"Middlesbrough",
			"Bratislava",
			"Dharamshala",
			"Asnieres-sur-Oise",
			"Chichicastenango",
			"Saint-Etienne",
			"Ouagadougou",
			"Yamoussoukro",
			"Alexandroupolis",
			"Gelsenkirchen",
			"Salzkammergut",
			"Clermont-Ferrand",
			"Saint-Germain-en-Laye"
		}, 45,
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to299, 100, 35f, 0.1f, 5f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to299, 100, 40f, 0, 5f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to343, 90, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to299, 100, 30f, 0.1f, 5f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to299, 100, 40f, 0, 4f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to343, 100, 35f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to299, 100, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to299, 100, 40f, 0, 3f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 90, 30f, 0.1f, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to200, 100, 30f, 0.1f, 5f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to200, 100, 40f, 0, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to200, 100, 30f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to200, 100, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to200, 100, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to200, 95, 35f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 100, 30f, 0.2f, 4f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to299, 90, 35f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 100, 30f, 0.2f, 3f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to200, 100, 10f, 0, 10f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to200, 100, 20f, 0, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to200, 90, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to200, 90, 35f, 0.3f, 3f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to200, 90, 40f, 0.2f, 2.5f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to200, 100, 30f, 0.2f, 3f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to299, 90, 35f, 0.3f, 3f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to299, 100, 40f, 0.2f, 2.5f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to299, 80, 40f, 0.3f, 2.5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 100, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 90, 30f, 0.3f, 3f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 80, 40f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 100, 30f, 0.2f, 4f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 90, 35f, 0.3f, 3f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to299, 80, 30f, 0.1f, 3f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 90, 30f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 80, 35f, 0.3f, 2.5f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 70, 40f, 0.3f, 4f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 90, 35f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 100, 30f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 80, 35f, 0.3f, 5f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 70, 35f, 0.2f, 4.5f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 60, 40f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 50, 40f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 40, 45f, 0.1f, 3.5f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 30, 45f, 0.1f, 3f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 30, 50f, 0.1f, 2.5f)
		),
		new Package(4, new string[]{
			"acorn",
			"squash",
			"alfalfa",
			"sprouts",
			"almond",
			"anchovy",
			"anise",
			"apple",
			"apricot",
			"aspic",
			"ate",
			"avocado",
			"bacon",
			"bagel",
			"bake",
			"banana",
			"barbecue",
			"barley",
			"basil",
			"batter",
			"beancurd",
			"bitter",
			"bland",
			"boil",
			"bowl",
			"bran",
			"bread",
			"breadfruit",
			"breakfast",
			"brisket",
			"broccoli",
			"broil",
			"brownie",
			"brunch",
			"buckwheat",
			"buns",
			"burrito",
			"butter",
			"cake",
			"calorie",
			"casserole",
			"cater",
			"caviar",
			"celery",
			"cereal",
			"chard",
			"cheddar",
			"cheese",
			"cheesecake",
			"chef",
			"cherry",
			"chew",
			"chicken",
			"chili",
			"chips",
			"chives",
			"chocolate",
			"chopsticks",
			"chow",
			"chutney",
			"cilantro",
			"cinnamon",
			"citron",
			"cook",
			"cookbook",
			"cookie",
			"corn",
			"cornflakes",
			"cornmeal",
			"crab",
			"crackers",
			"cranberry",
			"cream",
			"crepe",
			"crisp",
			"crunch",
			"crust",
			"cucumber",
			"cuisine",
			"cupboard",
			"cupcake",
			"curds",
			"currants",
			"curry",
			"custard",
			"daikon",
			"dairy",
			"dates",
			"dessert",
			"diet",
			"digest",
			"dill",
			"dine",
			"diner",
			"dish",
			"dough",
			"doughnut",
			"dragonfruit",
			"dressing",
			"dried",
			"drink",
			"dry",
			"durian",
			"snack",
			"soda",
			"sole",
			"soup",
			"sour",
			"soy",
			"steak",
			"stew",
			"stove",
			"straw",
			"suet",
			"sugar",
			"supper",
			"sushi",
			"sweet",
			"syrup",
			"taco",
			"taro",
			"tart",
			"tea",
			"tuber",
			"tuna",
			"veal",
			"wafer",
			"waffle",
			"walnut",
			"wasabi",
			"water",
			"wheat",
			"whey",
			"wok",
			"yam",
			"yeast",
			"yogurt",
			"yolk",
			"eat",
			"edible",
			"egg",
			"eggplant",
			"endive",
			"entree",	
			"fast",
			"fat",
			"feast",
			"fed",
			"feed",
			"fennel",
			"fig",
			"fillet",
			"fire",
			"fish",
			"flan",
			"flax",
			"flour",
			"food",
			"fork",
			"freezer",
			"fried",
			"fritter",
			"frosting",
			"fruit",
			"fry",
			"ribs",
			"rice",
			"roast",
			"roll",
			"garlic",
			"gelatin",
			"ginger",
			"gingerale",
			"glasses",
			"grain",
			"granola",
			"grape",
			"grapefruit",
			"grated",
			"gravy",
			"greenbean",
			"greens",
			"grub",
			"guacamole",
			"guava",
			"gyro",
			"herbs",
			"halibut",
			"ham",
			"hamburger",
			"hash",
			"hazelnut",
			"herbs",
			"honey",
			"honeydew",
			"horseradish",
			"hot",
			"hummus",
			"hunger",
			"hungry",
			"ice",
			"icing",
			"jackfruit",
			"jalapeno",
			"jam",
			"jelly",
			"jellybeans",
			"jicama",
			"jimmies",
			"jug",
			"julienne",
			"juice",
			"kale",
			"kebab",
			"ketchup",
			"kettle",
			"kitchen",
			"kiwi",
			"knife",
			"kohlrabi",
			"kumquat",
			"ladle",
			"lamb",
			"lard",
			"lasagna",
			"legumes",
			"lemon",
			"lemonade",
			"lentils",
			"lettuce",
			"licorice",
			"lime",
			"liver",
			"loaf",
			"lobster",
			"lollipop",
			"loquat",
			"lox",
			"lunch",
			"lunchmeat",
			"lychee",
			"macaroni",
			"macaroon",
			"maize",
			"mango",
			"meat",
			"meatball",
			"meatloaf",
			"melon",
			"menu",
			"meringue",
			"milk",
			"milkshake",
			"millet",
			"mincemeat",
			"minerals",
			"mint",
			"mints",
			"mochi",
			"molasses",
			"mozzarella",
			"muffin",
			"mug",
			"munch",
			"mushroom",
			"mussels",
			"mustard",
			"mutton",
			"napkin",
			"nectar",
			"nectarine",
			"nibble",
			"noodles",
			"nosh",
			"nourish",
			"nourishment",
			"nut",
			"nutmeg",
			"nutrient",
			"nutrition",
			"nutritious",
			"oats",
			"oatmeal",
			"oil",
			"okra",
			"oleo",
			"olive",
			"omelet",
			"onion",
			"orange",
			"order",
			"oregano",
			"oven",
			"oyster",
			"pan",
			"pancake",
			"papaya",
			"parsley",
			"parsnip",
			"pasta",
			"pastry",
			"pate",
			"patty",
			"peach",
			"peanut",
			"pea",
			"pear",
			"pecan",
			"peapod",
			"pepper",
			"pepperoni",
			"pickle",
			"picnic",
			"pie",
			"pilaf",
			"pineapple",
			"pitcher",
			"pomelo",
			"pop",
			"popsicle",
			"popcorn",
			"popovers",
			"pork",
			"pot",
			"potato",
			"preserves",
			"pretzel",
			"protein",
			"provisions",
			"prune",
			"pudding",
			"pumpkin",
			"punch",
			"quiche",
			"quinoa",
			"radish",
			"raisin",
			"raspberry",
			"rations",
			"ravioli",
			"recipe",
			"relish",
			"restaurant",
			"rhubarb",
			"romaine",
			"rosemary",
			"rye",
			"saffron",
			"sage",
			"salad",
			"salami",
			"salmon",
			"salsa",
			"salt",
			"sandwich",
			"sauce",
			"sauerkraut",
			"sausage",
			"savory",
			"scallops",
			"scrambled",
			"seaweed",
			"seeds",
			"shallots",
			"sherbet",
			"shrimp",
			"slaw",
			"slice",
			"smoked",
			"sorbet",
			"sorghum",
			"sorrel",
			"soybeans",
			"soysauce",
			"spaghetti",
			"spareribs",
			"spatula",
			"spuds",
			"squash",
			"squid",
			"stir-fry",
			"stomach",
			"strawberry",
			"stringy",
			"strudel",
			"succotash",
			"sundae",
			"sunflower",
			"sustenance",
			"take-out",
			"tamale",
			"tangerine",
			"tapioca",
			"tarragon",
			"teapot",
			"teriyaki",
			"thyme",
			"toast",
			"toaster",
			"tomato",
			"torte",
			"tortilla",
			"turkey",
			"turmeric",
			"turnip",
			"unleavened",
			"utensils",
			"vanilla",
			"vegetable",
			"venison",
			"vinegar",
			"vitamin",		
			"watercress",
			"watermelon",
			"zucchini",
			"refreshments",
			"refrigerator",
			"pumpernickel",
			"persimmon",
			"omnivore",
			"micronutrient",
			"gastronomy",
			"gingerbread",
			"foodstuffs",
			"elderberry",
			"comestibles",
			"cauliflower",
			"blackberry",
			"blueberry",
			"boysenberry",
			"appetizer",
			"appetite",
			"artichoke",
			"asparagus"
		}, 45,
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to299, 100, 35f, 0.1f, 5f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to299, 100, 40f, 0, 5f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to343, 90, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to299, 100, 30f, 0.1f, 5f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to299, 100, 40f, 0, 4f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to343, 100, 35f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to299, 100, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to299, 100, 40f, 0, 3f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 90, 30f, 0.1f, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to200, 100, 30f, 0.1f, 5f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to200, 100, 40f, 0, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to200, 100, 30f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to200, 100, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to200, 100, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to200, 95, 35f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 100, 30f, 0.2f, 4f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to299, 90, 35f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 100, 30f, 0.2f, 3f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to200, 100, 10f, 0, 10f),
			new Package.Stage (GameScript.GamePattern.minRespawn, GameScript.GameLevel.to200, 100, 20f, 0, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to200, 90, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to200, 90, 35f, 0.3f, 3f),
			new Package.Stage (GameScript.GamePattern.speed, GameScript.GameLevel.to200, 90, 40f, 0.2f, 2.5f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to200, 100, 30f, 0.2f, 3f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to299, 90, 35f, 0.3f, 3f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to299, 100, 40f, 0.2f, 2.5f),
			new Package.Stage (GameScript.GamePattern.damage, GameScript.GameLevel.to299, 80, 40f, 0.3f, 2.5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 100, 30f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 90, 30f, 0.3f, 3f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 80, 40f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 100, 30f, 0.2f, 4f),
			new Package.Stage (GameScript.GamePattern.item, GameScript.GameLevel.to299, 90, 35f, 0.3f, 3f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to299, 80, 30f, 0.1f, 3f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 90, 30f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 80, 35f, 0.3f, 2.5f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 70, 40f, 0.3f, 4f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 90, 35f, 0.2f, 5f),
			new Package.Stage (GameScript.GamePattern.bomb, GameScript.GameLevel.to343, 100, 30f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 80, 35f, 0.3f, 5f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 70, 35f, 0.2f, 4.5f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 60, 40f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 50, 40f, 0.1f, 4f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 40, 45f, 0.1f, 3.5f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 30, 45f, 0.1f, 3f),
			new Package.Stage (GameScript.GamePattern.bombItem, GameScript.GameLevel.to343, 30, 50f, 0.1f, 2.5f)
		)
	};

	public static void init(){
		if (Application.systemLanguage.Equals (SystemLanguage.Korean)) {
			StringMainHelpRemoveAd = "광고 제거";
			StringMainHelpSavingMode = "절전 모드";
			StringMainHelpAboutGame = "게임에 대해";
			StringMainHelpAboutItem = "아이템에 대해";
			StringMainQuitMessage = "뒤로 버튼을 한 번 더 누르시면 종료됩니다";
			StringQuitMessage = "게임을 종료하시겠습니까?";
			StringQuitConfirm = "확인";
			StringPanelCancel = "취소";
			StringNoKeyMessage = "미끼가 부족합니다.";
			StringNoKeyConfirm = "미끼 구매";
			StringGameReady = "준비";
			StringGameStart = "시작";
			StringGameResultEarnedExp = "획득 경험치";
			StringGameResultEarnedItem = "획득 아이템";
			StringGameResultNeedItem = "아이템이 부족한가요?";
			StringGameReviewMessage = "시간이 남는다면 리뷰를 남겨주세요.";
			StringGameReviewConfirm = "리뷰 하기";
			StringShopItemButtonTitle [0] = "미끼 10개";
			StringShopItemButtonTitle [1] = "광고보고 열쇠 1개";
			StringShopItemButtonTitle [2] = "아이템 지우개 10개";
			StringShopItemButtonTitle [3] = "아이템 비 10개";
			StringShopItemButtonTitle [4] = "아이템 모래시계 10개";
			StringShopItemButtonTitle [5] = "아이템 회복 10개";
			StringShopItemButtonTitle [6] = "아이템 폭탄방지 10개";
			StringShopItemButtonTitle [7] = "아이템 지우개+비 10개 팩";
			StringShopItemButtonTitle [8] = "광고 제거";
			StringShopPackageButtonTitle [0] = "패키지 TOEIC";
			StringShopPackageButtonTitle [1] = "패키지 TOFLE";
			StringShopItemButton1Money = "광고 시청";
			StringShopItemButton8Explain = "게임 후 나오는 광고를 제거합니다.";
			StringShopButtonPurchased = "구매 완료";
			StringShopCatMessage = "둘러보게냥.";
			StringHelpGameTutorial [0] = "영단어 잡기 게임은 정확한 발음을 위한\n키보드 모드와 스피치 모드가 있습니다.";
			StringHelpGameTutorial [1] = "먼저 키보드 모드 기준으로 게임을 소개합니다.";
			StringHelpGameTutorial [2] = "플레이어 바는 플레이어의 레벨과 체력, 5 종류의 아이템과 남은 시간이 표시되어 있습니다.\n아이템은 터치하는 것으로 사용되고 마지막 아이템인 폭탄 방지 아이템은 폭탄이 터질 경우 자동으로 소비됩니다.";
			StringHelpGameTutorial [3] = "시간이 흐르면 단어가 내려옵니다. 단어 옆에는 얻을 수 있는 경험치가 표시되어 있습니다. 키보드로 타이핑하면 입력 창에 입력됩니다.";
			StringHelpGameTutorial [4] = "내려오는 단어가 키보드 자판에 닿기 전까지 입력 창에 타이핑해서 맞춰야 합니다.";
			StringHelpGameTutorial [5] = "단어를 맞추면 맞춘 단어를 읽어줍니다. 또 단어의 난이도에 따라 다른 경험치를 얻습니다. 얻은 경험치는 우측 하단에 나타났다가 사라집니다.";
			StringHelpGameTutorial [6] = "랜덤 아이템 단어를 맞추면 일정 확률로 랜덤의 아이템이 발동합니다. 이 중에는 낮은 확률이지만 폭탄이 포함되어 있어 이 단어를 맞추지 않는 것이 나을 수도 있습니다.";
			StringHelpGameTutorial [7] = "게임은 남은 시간이 0이 되면 게임 클리어 됩니다. 게임 클리어 전에 체력이 0이 되면 게임 오버 됩니다.";
			StringHelpGameTutorial [8] = "스피치 모드일 경우 자판 대신 스피치 버튼이 나타납니다.";
			StringHelpGameTutorial [9] = "스피치 버튼을 터치하고 말을 하면 음성 인식을 통해 입력 창에 단어를 입력할 수 있습니다. 음성 인식이 끝난 후에도 단어가 입력되지 않는 경우는 에러가 발생한 경우이니 다시 입력해주시길 바랍니다.";
			StringHelpGameTutorial [10] = "정확하게 단어를 맞추면 추가 경험치를 얻습니다. 단어의 정확도는 검정, 회색, 빨강 순으로 검정은 정확하게 단어를 맞춘 경우, 회색은 부정확하게 단어를 맞추는 경우, 빨강은 틀린 경우로 인식된 단어 중 가장 유력한 단어를 보여줍니다.";
			StringHelpGameTutorial [11] = "기본을 선택해주세요.";
			StringHelpItemTutorial [0] = "영단어 잡기 게임의 아이템을 소개합니다.";
			StringHelpItemTutorial [1] = "아이템 지우개를 터치하면 가장 아래에 있는 단어가 사라집니다.";
			StringHelpItemTutorial [2] = "아이템 비를 터치하면 화면 상의 모든 단어가 사라집니다.";
			StringHelpItemTutorial [3] = "아이템 모래시계를 터치하면 3초간 시간이 멈춥니다. 이 시간 동안 단어를 맞출 수 있습니다.";
			StringHelpItemTutorial [4] = "아이템 회복을 터치하면 일정량 체력을 회복합니다.";
			StringHelpItemTutorial [5] = "아이템 폭탄 방지는 터치해서 사용할 수 없고 랜덤 아이템 단어를 맞출 경우 낮은 확률로 발동하는 폭탄 효과를 막습니다.";
			StringHelpItemTutorial [6] = "아이템은 특정 스테이지를 클리어하면 확률적으로 얻을 수 있습니다.";
			StringHelpPlayerBar = "플레이어 바";
			StringHelpWord = "단어";
			StringHelpInputBar = "입력 바";
			StringHelpTargetWord = "맞출 단어";
			StringHelpCatchedWord = "맞춘 단어";
			StringHelpTyping = "타이핑";
			StringHelpRandomItemWord = "랜덤 아이템 단어";
			StringHelpRemainTime = "남은 시간";
			StringHelpSpeechButton = "스피치 버튼";
			StringHelpSpeechVolume = "음성 볼륨";
			StringHelpTypedWord = "입력된 단어";
			StringHelpRemoverItem = "아이템 지우개";
			StringHelpWordToDisappear = "사라질 단어";
			StringHelpRainItem = "아이템 비";
			StringHelpWordsToDisappear = "사라질 단어들";
			StringHelpSandglassItem = "아이템 모래시계";
			StringHelpHPBar = "HP 바";
			StringHelpRecoverItem = "아이템 회복";
			StringHelpBombPreventerItem = "아이템 폭탄 방지";
			StringHelpForiOS = "돌아가려면 아래로 슬라이드";
		} else if (Application.systemLanguage.Equals (SystemLanguage.Japanese)) {
			StringMainHelpRemoveAd = "CMを消す";
			StringMainHelpSavingMode = "省電力モード";
			StringMainHelpAboutGame = "ゲームについて";
			StringMainHelpAboutItem = "アイテムについて";
			StringMainQuitMessage = "バックキーをもう一度押すと終了します";
			StringQuitMessage = "ゲームを終了しますか。";
			StringQuitConfirm = "OK";
			StringPanelCancel = "キャンセル";
			StringNoKeyMessage = "餌が足りません。";
			StringNoKeyConfirm = "餌を買う";
			StringGameReady = "レディー";
			StringGameStart = "スタート";
			StringGameResultEarnedExp = "得た経験値";
			StringGameResultEarnedItem = "得たアイテム";
			StringGameResultNeedItem = "アイテムが足りませんか。";
			StringGameReviewMessage = "時間が余るのならリビューを残してください。";
			StringGameReviewConfirm = "リビューする";
			StringShopItemButtonTitle [0] = "えさ 10こ";
			StringShopItemButtonTitle [1] = "CMみてからえさ 1こ";
			StringShopItemButtonTitle [2] = "アイテム けしごむ 10こ";
			StringShopItemButtonTitle [3] = "アイテム あめ 10こ";
			StringShopItemButtonTitle [4] = "アイテム すなどけい 10こ";
			StringShopItemButtonTitle [5] = "アイテム かいふく 10こ";
			StringShopItemButtonTitle [6] = "アイテム ばくだんふせぎ 10こ";
			StringShopItemButtonTitle [7] = "アイテム けしごむ＋あめ 10こ パック";
			StringShopItemButtonTitle [8] = "CMをけす";
			StringShopPackageButtonTitle [0] = "パッケージ 1";
			StringShopPackageButtonTitle [1] = "パッケージ 2";
			StringShopItemButton1Money = "CMをみる";
			StringShopItemButton8Explain = "ゲームの後のCMを消します。";
			StringShopButtonPurchased = "購入完了";
			StringShopCatMessage = "みていって\nニャー";
			StringHelpGameTutorial [0] = "キャッチーワードゲームには正確な発音の為に、キボードモードとスピーチモードがあります。";
			StringHelpGameTutorial [1] = "まず、キボードモードを基本にゲームをご紹介します。";
			StringHelpGameTutorial [2] = "プレーヤーバーはプレーヤーのレベル、HP、５種類のアイテム、そして残り時間を表示します。\nアイテムはタッチすることで使用できます。ただ、最後のアイテムの爆弾防ぎアイテムは爆弾が発動する時、自動に消費されます。";
			StringHelpGameTutorial [3] = "時間が経つと単語が降りてきます。　単語の隣には得られる経験値が表示されてます。　キボードでタイピングすると入力されます。";
			StringHelpGameTutorial [4] = "降りてくる単語がキボードに当たる前に入力バーにタイピングして当てましょう。";
			StringHelpGameTutorial [5] = "単語を当てると当てた単語を読み上げます。　また、単語の難易度について違う経験値を得られます。　得た経験値は右下段に現れて消えて行きます。";
			StringHelpGameTutorial [6] = "ランダムアイテム単語を当てると一定確率でランダムのアイテムが発動します。　この中では低い確率だけど爆弾が含まれていて、この単語は当てない方がマシかも知れません。";
			StringHelpGameTutorial [7] = "ゲームは残り時間が０になるとゲームクリアします。　ゲームクリア前にHPが０になればゲームオーバーします。";
			StringHelpGameTutorial [8] = "スピーチモードの場合、キーボドの代わりにスピーチボタンが現れます。";
			StringHelpGameTutorial [9] = "スピーチボタンをタッチしてから喋ると音声認識を通じ入力バーに単語を入力することができます。　音声認識が終わってからも単語が入力されない場合、エラーが発生したことですので改めて入力してください。";
			StringHelpGameTutorial [10] = "正確に単語を当てると追加経験値が得られます。　単語の正確度は黒、グレイ、赤の準番で、黒は正確に単語を当てた時、グレイは不正確に単語を当てた時、そして、赤は不正解の場合で、認識された単語の中で一番有力な単語を見せます。";
			StringHelpGameTutorial [11] = "基本を選んでください。";
			StringHelpItemTutorial [0] = "キャッチーワードゲームのアイテムをご紹介します。";
			StringHelpItemTutorial [1] = "アイテム　消しゴムをタッチすると一番下の単語が消えます。";
			StringHelpItemTutorial [2] = "アイテム　雨をタッチすると画面上の全ての単語が消えます。";
			StringHelpItemTutorial [3] = "アイテム　砂時計をタッチすると３秒間時間が止まります。　この時間の間に単語が当てられます。";
			StringHelpItemTutorial [4] = "アイテム　回復をタッチすると一定量のHPを回復します。";
			StringHelpItemTutorial [5] = "アイテム　爆弾防ぎはタッチして使用できません。　このアイテムはランダムアイテム単語を当てた時、低い確率で発動する爆弾を止めます。";
			StringHelpItemTutorial [6] = "アイテムは特定のステージをクリアすると確率的に得られます。";
			StringHelpPlayerBar = "プレーヤーバー";
			StringHelpWord = "単語";
			StringHelpInputBar = "入力バー";
			StringHelpTargetWord = "当てる単語";
			StringHelpCatchedWord = "当てた単語";
			StringHelpTyping = "タイピング";
			StringHelpRandomItemWord = "ランダムアイテム単語";
			StringHelpRemainTime = "残り時間";
			StringHelpSpeechButton = "スピーチボタン";
			StringHelpSpeechVolume = "スピーチボリューム";
			StringHelpTypedWord = "入力された単語";
			StringHelpRemoverItem = "アイテム　消しゴム";
			StringHelpWordToDisappear = "消える単語";
			StringHelpRainItem = "アイテム　雨";
			StringHelpWordsToDisappear = "消える単語たち";
			StringHelpSandglassItem = "アイテム　砂時計";
			StringHelpHPBar = "HPバー";
			StringHelpRecoverItem = "アイテム　回復";
			StringHelpBombPreventerItem = "アイテム　爆弾防ぎ";
			StringHelpForiOS = "下にスワイプして戻る";
		} else {
			StringMainHelpRemoveAd = "Ad Removing";
			StringMainHelpSavingMode = "Power Save Mode";
			StringMainHelpAboutGame = "About Game";
			StringMainHelpAboutItem = "About Item";
			StringMainQuitMessage = "Press the Back button again to exit";
			StringQuitMessage = "Do you quit the game?";
			StringQuitConfirm = "Confirm";
			StringPanelCancel = "Cancel";
			StringNoKeyMessage = "You don't have a bait.";
			StringNoKeyConfirm = "Get a bait";
			StringGameReady = "Ready";
			StringGameStart = "Start";
			StringGameResultEarnedExp = "Earned Exp";
			StringGameResultEarnedItem = "Earned Item";
			StringGameResultNeedItem = "Do you need some items?";
			StringGameReviewMessage = "Please leave a review if you have time.";
			StringGameReviewConfirm = "Reviews";
			StringShopItemButtonTitle [0] = "10 Bait";
			StringShopItemButtonTitle [1] = "Ad for 1 bait";
			StringShopItemButtonTitle [2] = "10 Remover Item";
			StringShopItemButtonTitle [3] = "10 Rain Item";
			StringShopItemButtonTitle [4] = "10 Sandglass Item";
			StringShopItemButtonTitle [5] = "10 Recovery Item";
			StringShopItemButtonTitle [6] = "10 Bomb Preventer Item";
			StringShopItemButtonTitle [7] = "10 Remover+Rain Item Pack";
			StringShopItemButtonTitle [8] = "Ad Removing";
			StringShopPackageButtonTitle [0] = "Package 1";
			StringShopPackageButtonTitle [1] = "Package 2";
			StringShopItemButton1Money = "Watch the ad";
			StringShopItemButton8Explain = "It removes ads after the game.";
			StringShopButtonPurchased = "Purchased";
			StringShopCatMessage = "Take a look.";
			StringHelpGameTutorial [0] = "The Catch Word game has keyboard mode and speech mode for accurate pronunciation.";
			StringHelpGameTutorial [1] = "First, we introduce the game based on keyboard mode.";
			StringHelpGameTutorial [2] = "The player bar shows the player's level, HP, 5 items and time remaining.\nThe item is used by touching, however, the last item, bomb preventer item, is automatically consumed if a bomb explodes.";
			StringHelpGameTutorial [3] = "The word comes down over time. Next to the word is the experience you can get. When typing with the keyboard, it is entered in the input bar.";
			StringHelpGameTutorial [4] = "You have to type in the input bar until the down word reaches the keyboard.";
			StringHelpGameTutorial [5] = "When you match a word, it reads the matching word. You will also get different experience depending on the difficulty of the word. The experience gained appears at the bottom right and disappears.";
			StringHelpGameTutorial [6] = "When you match the random item word, random items will appear as chance of chance. This may be a low probability, but it may be better not to match it because it contains bombs.";
			StringHelpGameTutorial [7] = "The game is cleared when the remaining time reaches zero. The game is over when the HP reaches 0 before clearing the game.";
			StringHelpGameTutorial [8] = "In speech mode, a speech button appears instead of a keyboard.";
			StringHelpGameTutorial [9] = "If you touch the Speech button and speak, you can enter words into the input bar through speech recognition. If the word is not entered after the speech recognition is finished, please input it again.";
			StringHelpGameTutorial [10] = "Matching the words correctly will give you additional experience. The accuracy of the words is in order of black, gray, red. the black is correct word, the gray is inaccurate word and the red shows the most likely word of the wrong answer.";
			StringHelpGameTutorial [11] = "Please select the default.";
			StringHelpItemTutorial [0] = "We introduce the items of the Catch Word game.";
			StringHelpItemTutorial [1] = "When you touch the item remover, the word at the bottom disappears.";
			StringHelpItemTutorial [2] = "When you touch an item rain, all words on the screen disappear.";
			StringHelpItemTutorial [3] = "When you touch the item sandglass, the time stops for 3 seconds. During this time you can match the words.";
			StringHelpItemTutorial [4] = "When you touch the item recovery, regain a certain amount of HP.";
			StringHelpItemTutorial [5] = "The item bomb preventer can not be used by touching, and if you match random item words, it prevents low-probability bombing.";
			StringHelpItemTutorial [6] = "An item can be stochastically obtained by clearing a certain stage.";
			StringHelpPlayerBar = "Player Bar";
			StringHelpWord = "Word";
			StringHelpInputBar = "Input Bar";
			StringHelpTargetWord = "Target Word";
			StringHelpCatchedWord = "Catched Word";
			StringHelpTyping = "Typing";
			StringHelpRandomItemWord = "Random Item Word";
			StringHelpRemainTime = "Remaining Time";
			StringHelpSpeechButton = "Speech Button";
			StringHelpSpeechVolume = "Speech Volume";
			StringHelpTypedWord = "Typed Word";
			StringHelpRemoverItem = "Item Remover";
			StringHelpWordToDisappear = "Word to disappear";
			StringHelpRainItem = "Item Rain";
			StringHelpWordsToDisappear = "Words to disappear";
			StringHelpSandglassItem = "Item Sandglass";
			StringHelpHPBar = "HP Bar";
			StringHelpRecoverItem = "Item Recovery";
			StringHelpBombPreventerItem = "Item Bomb Preventer";
			StringHelpForiOS = "Slide down to go back";
		}
	}

}
