using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LocalizationString : MonoBehaviour
{
    public static bool isInitailized;

    public static string LOGIN_network;
    public static string LOGIN_version;
    public static string LOGIN_otherwork;
    public static string LOGOLOGIN_networkerror;
    public static string LOGOLOGIN_networktimeover;
    public static string LOGIN_WarningNicknameContains;
    public static string LOGIN_WarningNickname;
    public static string LOGIN_WarningEmailLength;
    public static string LOGIN_WarningEmail;
    public static string LOGIN_WarningEmailAlready;
    public static string LOGIN_WarningNicknameAlready;
    public static string LOGIN_WarningUnknown;
    public static string LOGIN_WarningDatabase;
    public static string LOGIN_WarningServerError;
    public static string LOGIN_WarningNoNick;
    public static string LOGIN_WarningWrongPin;
    public static string LOGIN_FailSocialLogin;
    public static string LOGIN_WaitingForToken;
    public static string LOGIN_CheckVersion;
    public static string LOGIN_NicknameDuple;
    public static string LOGIN_LoginDuple;
    public static string LOGIN_LoginFail;
    public static string LOGIN_LoginExpiredFail;
    public static string LOGIN_NicknameEmpty;
    public static string LOGIN_IDPWEmpty;
    public static string LOGIN_InvalidNickname;
    public static string LOGIN_InvalidID;
    public static string LOGIN_InvalidPW;
    public static string LOGIN_NotLogined;
    public static string LOGIN_Block;
    public static string LOGIN_DiffPwMessage;
    public static string MAINGAME_NickPopupMessage;
    public static string MAINGAME_WarningVerrify;
    public static string MAINGAME_FriendListFail;
    public static string MAINGAME_GoingSquare;
    public static string MAINGAME_VisitMessage;
    public static string MAINGAME_VisitantMessage;
    public static string MAINGAME_GoingHome;
    public static string MAINGAME_MasterLeave;
    public static string MAINGAME_GuestBusy;
    public static string MAINGAME_BuyingMessage;
    public static string MAINGAME_SuccessToBuy;
    public static string MAINGAME_NotEnoughGem;
    public static string MAINGAME_PutFurnitureMessage;
    public static string MAINGAME_BlockMessage;
    public static string MAINGAME_UnblockMessage;
    public static string MAINGAME_FriendLimitMessage;
    public static string MAINGAME_FriendAddMessage;
    public static string MAINGAME_FriendRemoveMessage;
    public static string MAINGAME_FashionshowEnterMessage;
    public static string MAINGAME_FashionshowWaitMessage;
    public static string MAINGAME_FashionshowRemainMessage;
    public static string MAINGAME_FashionshowCancelMessage;
    public static string MAINGAME_FashionshowScoreLimitMessage;
    public static string MAINGAME_FashionshowScoreMessage;
    public static string MAINGAME_FashionshowScore0Message;
    public static string MAINGAME_FashionshowDisabled;
    public static string MAINGAME_yes;
    public static string MAINGAME_no;
    public static string MAINGAME_confirm;
    public static string MAINGAME_WrongOccured;
    public static string MAINGAME_NickScoreMessage;
    public static string MAINGAME_NickScoreListMessage;
    public static string MAINGAME_NoUserMessage;
    public static string MAINGAME_ProfileEditMessage;
	public static string MAINGAME_FountainCoinThrowingMessage;
	public static string MAINGAME_FountainCoinThrownMessage;
	public static string MAINGAME_FountainLessCashMessage;
	public static string MAINGAME_FountainInvalidCoinMessage;
    public static string MSG_FriendRequestMessage;
    public static string MSG_FriendAcceptMessage;
    public static string MSG_FriendRefuseMessage;
    public static string MSG_FriendDeleteMessage;
    public static string MSG_FriendRequestSended;
    public static string MSG_FriendRequestReceived;
    public static string MSG_VisitRequestMessage;
    public static string MSG_FriendDupleMessage;
    public static string MSG_FriendFailToRequestMessage;
    public static string MSG_FriendFailToAcceptMessage;
    public static string MSG_FailToWatchMessage;
    public static string MSG_Quit;
    public static string MSG_Update;
    public static string MSG_MsgAccepted;
    public static string MSG_UnlockSlotMessage;
    public static string MSG_SaveSlotMessage;
    public static string MSG_LoadSlotMessage;
    public static string MSG_ExitChatMessage;
    public static string MSG_DiaryBlockMessage;
    public static string MSG_DiaryNotFriendMessage;
    public static string MSG_DiaryAddMessage;
    public static string MSG_DiaryEditMessage;
    public static string MSG_DiarDeleteMessage;
    public static string MSG_DiaryAddReplyMessage;
    public static string MSG_DiaryEditReplyMessage;
    public static string MSG_DiaryDeleteReplyMessage;
    public static string MSG_DiaryEmptyMessage;
	public static string MSG_AdoptRaiseMessage;
	public static string MSG_AdoptDeleteMessage;
    public static string MINIGAME_exitMessage;
    public static string MINIGAME_scoreMessage;
    public static string MINIGAME_PartnerLeave;
    public static string MINIGAME_DiceGameEnterMessage;
    public static string MINIGAME_FootholdGameEnterMessage;
    public static string MAINGAME_FootholdGameRuleMessage;
    public static string MINIGAME_BlindDateEnterMessage;
    public static string MINIGAME_FailToScoreMessage;
    public static string MAINGAME_ChChangeMessage;
    public static string MAINGAME_GoSlotMessage;
    public static string MAINGAME_FishingGameEnterMessage;
	public static string MAINGAME_GoPianoMessage;
	public static string MAINGAME_HangmanGameEnterMessage;
	public static string MAINGAME_HangmanGameRuleMessage;
	public static string MINIGAME_RunningEnterMessage;
	public static string MINIGAME_RunningBettingMessage;
	public static string MINIGAME_RunningGameRuleMessage;
    public static string SHOP_msg1;
    public static string SHOP_msg2;
    public static string SHOP_RandomClothMessage;
    public static string SHOP_RandomFurnitureMessage;
    public static string SHOP_GemMessage;
    public static string SHOP_GemEarnedMessage;
    public static string SHOP_DupleReceipt;
    public static string SHOP_FailToReceipt;
    public static string SHOP_InvalidReceipt;
    public static string SHOP_FullItemMessage;
    public static string SHOP_LessItemMessage;
    public static string SHOP_HaveItemMessage;
    public static string SHOP_SlotMessage;
    public static string OPTION_FashionshowView;
    public static string OPTION_Report;
    public static string OPTION_ReportSuccessMessage;
    public static string OPTION_ReportLimitMessage;
    public static string OPTION_BGM;
    public static string OPTION_SE;
    public static string OPTION_Speak;
    public static string OPTION_friendRequest;
    public static string OPTION_visitRequest;
    public static string Rule;
    public static string Gem;
    public static string Random;
    public static string Cloth;
    public static string Furniture;
    public static string DiceGame;
    public static string FootholdGame;
    public static string FishingCafe;
	public static string PianoRoom;
	public static string HangmanGame;
    public static string Diary;
    public static string GuestBook;
    public static string Write;
    public static string Edit;
    public static string Reply;
    public static string Delete;
    public static string Cancel;
    public static string Confirm;
    public static string Accept;
    public static string Refuse;
    public static string Result;
    public static string Report;
    public static string UserList;
    public static string Relationship;
    public static string Post;
    public static string Item;
    public static string Box;
    public static string Waiting;
    public static string Option;
    public static string Slot;
    public static string Save;
    public static string Load;
	public static string Fountain;
	public static string Rank;
	public static string CoinThrowing;
	public static string Stamina;
	public static string Running;
	public static string Speed;
	public static string Record;
	public static string Adopt;
	public static string Betting;
	public static string Sec;
    public static string PrivacyTerms;
    public static string Agree;
    public static string GoogleLogin;
    public static string GameCenterLogin;
    public static string GuestLogin;

    public static string[] access_level = new string[3];

    public static void initialize()
    {
        if (Application.systemLanguage == SystemLanguage.Korean)
        {
            LOGIN_network = "인터넷 상태를 확인하여 주세요";
            LOGIN_version = "게임을 최신 버전으로 업데이트 해 주세요";
            LOGIN_otherwork = "실시간 게임 중 게임을 멈추셔서 접속이 끊겼습니다";
            LOGOLOGIN_networkerror = "네트워크가 불안정합니다";
            LOGOLOGIN_networktimeover = "서버응답이 오래걸려 완료하지 못했습니다";
            LOGIN_WarningNicknameContains = "닉네임에 빈칸과 @를 포함할 수 없습니다";
            LOGIN_WarningNickname = "닉네임을 2~8자리의 글자로 입력해주세요";
            LOGIN_WarningEmailLength = "이메일을 8~30자리의 글자로 입력해주세요";
            LOGIN_WarningEmail = "이메일을 형식에 맞게 입력해주세요";
            LOGIN_WarningEmailAlready = "해당 이메일로는 이미 가입하셨습니다";
            LOGIN_WarningNicknameAlready = "해당 닉네임으로는 이미 가입하셨습니다";
            LOGIN_WarningUnknown = "서버에서 알수 없는 이유로 처리하지 못하였습니다";
            LOGIN_WarningDatabase = "데이터베이스 오류로 처리하지 못하였습니다";
            LOGIN_WarningServerError = "서버에서 오류가 발생하였습니다";
            LOGIN_WarningNoNick = "계정이 존재하지 않습니다";
            LOGIN_WarningWrongPin = "계정인증에 실패하였습니다";
            LOGIN_FailSocialLogin = "소셜 로그인에 실패하였습니다";
            LOGIN_WaitingForToken = "토큰을 받아오는 중 입니다";
            LOGIN_CheckVersion = "최신버전으로 업데이트가 필요합니다";
            LOGIN_NicknameDuple = "닉네임이 중복됩니다";
            LOGIN_LoginDuple = "다른 기기에서 로그인 되었습니다";
            LOGIN_LoginFail = "로그인에 실패했습니다";
            LOGIN_LoginExpiredFail = "로그인 기간이 만료되었습니다. 게임을 다시 시작해 주세요";
            LOGIN_NicknameEmpty = "닉네임이 빈칸입니다";
            LOGIN_IDPWEmpty = "ID 또는 비밀번호가 빈칸입니다";
            LOGIN_InvalidNickname = "닉네임에 빈칸과 @,/,\\,\"는 포함될 수 없습니다";
            LOGIN_InvalidID = "ID에 빈칸과 특수문자가 포함될 수 없습니다";
            LOGIN_InvalidPW = "비밀번호에 빈칸과 /,\\,\"는 포함될 수 없습니다";
            LOGIN_NotLogined = "로그인되어 있지 않습니다";
            LOGIN_Block = "{0} 까지 사용정지 상태입니다";
            LOGIN_DiffPwMessage = "이미 있는 아이디거나 비밀번호가 다릅니다";
            MAINGAME_NickPopupMessage = "닉네임을 입력해주세요";
            MAINGAME_WarningVerrify = "계정인증에 실패하였습니다";
            MAINGAME_FriendListFail = "친구 목록을 받아오지 못 했습니다";
            MAINGAME_GoingSquare = "광장으로 나가시겠습니까?";
            MAINGAME_VisitMessage = "{0}의 집에 방문 요청을 하시겠습니까?";
            MAINGAME_VisitantMessage = "{0}로부터 방문 요청이 왔습니다";
            MAINGAME_GoingHome = "집으로 돌아가시겠습니까?";
            MAINGAME_MasterLeave = "방 주인이 떠나 집으로 돌아왔습니다";
            MAINGAME_GuestBusy = "손님이 방문 가능한 상태가 아닙니다";
            MAINGAME_BuyingMessage = "{0} 보석로 구매하시겠습니까?";
            MAINGAME_SuccessToBuy = "구매에 성공했습니다";
            MAINGAME_NotEnoughGem = "보석이 부족합니다";
            MAINGAME_PutFurnitureMessage = "방에 놓으시겠습니까?";
            MAINGAME_BlockMessage = "차단하시겠습니까?";
            MAINGAME_UnblockMessage = "차단 해제하시겠습니까?";
            MAINGAME_FriendLimitMessage = "더 이상 친구를 만들 수 없습니다";
            MAINGAME_FriendAddMessage = "친구 요청하시겠습니까?";
            MAINGAME_FriendRemoveMessage = "친구 삭제하시겠습니까?";
            MAINGAME_FashionshowEnterMessage = "광고시청 후 패션쇼에 참가하시겠습니까?";
            MAINGAME_FashionshowWaitMessage = "다음 패션쇼까지 {0}분 {1}초 남았습니다";
            MAINGAME_FashionshowRemainMessage = "패션쇼 대기 인원 {0}명입니다";
            MAINGAME_FashionshowCancelMessage = "패션쇼 참가를 취소하시겠습니까?";
            MAINGAME_FashionshowScoreLimitMessage = "점수는 50점부터 100점까지 줄 수 있습니다";
            MAINGAME_FashionshowScoreMessage = "{1}명이 평가해서 {0} 님이 {2}점 받았습니다";
            MAINGAME_FashionshowScore0Message = "0명이 평가해서 {0} 님이 {1}점을 랜덤점수로 받았습니다";
            MAINGAME_FashionshowDisabled = "패션쇼 보기 옵션이 꺼져있습니다";
            MAINGAME_yes = "네";
            MAINGAME_no = "아니오";
            MAINGAME_confirm = "확인";
            MAINGAME_WrongOccured = "잘못된 요청입니다";
            MAINGAME_NickScoreMessage = "궁합을 보시겠습니까?";
            MAINGAME_NickScoreListMessage = "유저를 선택하세요";
            MAINGAME_ProfileEditMessage = "프로필 메시지를 입력해주세요";
            MAINGAME_FountainCoinThrowingMessage = "{0} 만큼 동전을 던지시겠습니까?";
			MAINGAME_FountainCoinThrownMessage = "{0} 만큼 동전을 던졌습니다";
			MAINGAME_FountainLessCashMessage = "가지고 있는 보석이 부족합니다";
			MAINGAME_FountainInvalidCoinMessage = "해당 갯수로 동전 던지기가 불가능합니다";
            MSG_FriendRequestMessage = "{0} 님으로부터 친구 요청이 왔습니다";
            MSG_FriendAcceptMessage = "{0} 님이 {1} 님의 친구 요청을 수락했습니다";
            MSG_FriendRefuseMessage = "{0} 님이 {1} 님의 친구 요청을 거절했습니다";
            MSG_FriendDeleteMessage = "{0} 님이 {1} 님을 친구 삭제했습니다";
            MSG_FriendRequestSended = "{0} 님에게 친구 요청했습니다";
            MSG_FriendRequestReceived = "{0} 님이 친구 요청했습니다";
            MSG_VisitRequestMessage = "{0} 님이 방문 요청했습니다";
            MSG_FriendDupleMessage = "이미 친구인 유저입니다";
            MSG_FriendFailToRequestMessage = "친구 요청하는데 실패했습니다";
            MSG_FriendFailToAcceptMessage = "친구 수락하는데 실패했습니다";
            MSG_FailToWatchMessage = "광고를 시청하는데 실패했습니다";
            MSG_Quit = "게임을 종료하시겠습니까?";
            MSG_Update = "잠시후 서버점검이 있겠습니다.";
            MSG_MsgAccepted = "{0} 님으로부터 쪽지를 받았습니다";
            MSG_UnlockSlotMessage = "{0}번 슬롯을 {1} 보석으로 구매하시겠습니까?";
            MSG_SaveSlotMessage = "{0}번 슬롯에 옷을 저장하시겠습니까?";
            MSG_LoadSlotMessage = "{0}번 슬롯을 불러오시겠습니까?";
            MSG_ExitChatMessage = "채팅방을 나가시겠습니까?";
            MSG_DiaryBlockMessage = "다이어리 주인으로부터 차단되었습니다";
            MSG_DiaryNotFriendMessage = "다이어리 주인과 친구가 아닙니다";
            MSG_DiaryAddMessage = "글을 등록하시겠습니까?";
            MSG_DiaryEditMessage = "글을 수정하시겠습니까?";
            MSG_DiarDeleteMessage = "글을 삭제하시겠습니까?";
            MSG_DiaryAddReplyMessage = "답글을 등록하시겠습니까?";
            MSG_DiaryEditReplyMessage = "답글을 수정하시겠습니까?";
            MSG_DiaryDeleteReplyMessage = "답글을 삭제하시겠습니까?";
            MSG_DiaryEmptyMessage = "제목 또는 내용이 빈칸입니다";
			MSG_AdoptRaiseMessage = "{0} 보석으로 해당 스테이터스를 올리시겠습니까?";
			MSG_AdoptDeleteMessage = "이 입양 슬롯을 삭제 하시겠습니까?";
            MAINGAME_NoUserMessage = "해당 유저가 접속중이 아닙니다";
            MINIGAME_exitMessage = "방을 나가시겠습니까?";
            MINIGAME_scoreMessage = "보석을 {0} 만큼 얻었습니다";
            MINIGAME_PartnerLeave = "{0} 님이 나가셨습니다";
            MINIGAME_DiceGameEnterMessage = "주사위 게임을 시작하시겠습니까?";
            MINIGAME_FootholdGameEnterMessage = "발판 게임을 시작하시겠습니까?";
            MAINGAME_FootholdGameRuleMessage = "제한 시간 동안 4개의 발판 중 한 곳을 선택하세요\n맞는 발판을 선택하면 보석을 얻습니다";
            MINIGAME_BlindDateEnterMessage = "소개팅 하러 가시겠습니까?";
            MINIGAME_FailToScoreMessage = "보석을 얻지 못했습니다";
            MAINGAME_ChChangeMessage = "채널 변경할까요?";
            MAINGAME_GoSlotMessage = "슬롯 방으로 이동하시겠습니까?";
            MAINGAME_FishingGameEnterMessage = "낚시 카페로 이동하시겠습니까?";
			MAINGAME_GoPianoMessage = "피아노 방으로 이동하시겠습니까?";
			MAINGAME_HangmanGameEnterMessage = "행맨 게임을 시작하시겠습니까?";
			MAINGAME_HangmanGameRuleMessage = "알파벳을 클릭해 단어를 맞혀주세요\n알파벳이 맞을 때마다 보석을 얻으며\n게임이 끝나고 가장 많이 맞힌 유저에게\n추가 보석이 주어집니다!";
			MINIGAME_RunningEnterMessage = "달리기 방으로 이동하시겠습니까?";
			MINIGAME_RunningBettingMessage = "베팅하시겠습니까?";
			MINIGAME_RunningGameRuleMessage = "6명의 캐릭터 중 한 명에게 베팅해주세요.\n1등을 맞추면 배당률x10만큼 보석을 얻습니다.\n베팅한 캐릭터를 응원해서 빠르게 할 수 있어요.\n해당 캐릭터 체력이 부족하면 응원할 수 없습니다.";
            SHOP_msg1 = "어서옵쇼~";
            SHOP_msg2 = "천천히 둘러보세요";
            SHOP_RandomClothMessage = "총 {0} 보석으로 랜덤 옷 상자 {1}개를 구매하시겠습니까?";
            SHOP_RandomFurnitureMessage = "총 {0} 보석으로 랜덤 가구 상자 {1}개를 구매하시겠습니까?";
            SHOP_GemMessage = "총 {0} 보석을 구매하시겠습니까?";
            SHOP_GemEarnedMessage = "보석이 {0} 개가 되었습니다";
            SHOP_DupleReceipt = "이미 지급된 영수증입니다";
            SHOP_FailToReceipt = "구매 실패했습니다";
            SHOP_InvalidReceipt = "잘못된 영수증입니다";
            SHOP_FullItemMessage = "모든 아이템을 구매했습니다";
            SHOP_LessItemMessage = "없는 아이템 수가 사려는 아이템 수보다 적습니다";
            SHOP_HaveItemMessage = "소유하고 있는 아이템입니다";
            SHOP_SlotMessage = "{0}번 슬롯 추가";
            OPTION_FashionshowView = "패션쇼 보기";
            OPTION_Report = "신고";
            OPTION_ReportSuccessMessage = "신고 성공했습니다";
            OPTION_ReportLimitMessage = "오늘 신고 횟수 10번을 모두 소진했습니다";
            OPTION_BGM = "배경음";
            OPTION_SE = "효과음";
            OPTION_Speak = "채팅 음성";
            OPTION_friendRequest = "친구 요청 허용";
            OPTION_visitRequest = "방문 요청 허용";
            Rule = "규칙";
            Gem = "보석";
            Random = "랜덤";
            Cloth = "옷";
            Furniture = "가구";
            DiceGame = "주사위 게임";
            FootholdGame = "발판 게임";
            FishingCafe = "낚시 카페";
			PianoRoom = "피아노 방";
			HangmanGame = "행맨 게임";
            Diary = "다이어리";
            GuestBook = "방명록";
            Write = "글쓰기";
            Reply = "답글";
            Edit = "수정";
            Delete = "삭제";
            Cancel = "취소";
            Confirm = "확인";
            Accept = "수락";
            Refuse = "거절";
            Result = "결과";
            Report = "신고";
            UserList = "유저 리스트";
            Relationship = "관계";
            Post = "쪽지";
            Item = "아이템";
            Box = "상자";
            Waiting = "대기 중";
            Option = "옵션";
            Slot = "슬롯";
            Save = "저장";
            Load = "불러오기";
			Fountain = "분수대";
			Rank = "순위";
			CoinThrowing = "동전 던지기";
			Stamina = "체력";
			Running = "달리기";
			Speed = "속도";
			Record = "기록";
			Adopt = "입양";
			Betting = "베팅";
			Sec = "초";
            PrivacyTerms = "FamilSoft는 이용자의 프라이버시를 매우 중요하게 생각하며 각별히 주의를 기울여 처리하고 있습니다.\n" +
                "이용자의 프라이버시를 존중하고 보호하기 위하여 FamilSoft는 다음의 기본 원칙을 마련하여 준수하고 있습니다.\n" +

                "1)FamilSoft는 이용자의 개인 정보를 수집, 처리, 사용 또는 공개하기 위해서 이를 적절한 방법에 따라 이용자에게 고지하고 동의를 구합니다.\n" +
                "2)FamilSoft는 이용자 개인 정보의 수집, 처리에 필요한 최소범위로 이용 목적을 특정합니다.\n" +
                "3)FamilSoft는 수집한 이용자의 개인정보에 대한 관리 책임{0} 만큼 동전을 던지시겠습니까?을 갖습니다.\n\n" +
                "어떤 정보를 수집합니까?\n" +
                " 1)계정 아이디와 2)행운의 옷장 게임 내 결제 내역을 수집합니다.\n" +
                " 앱을 재설치한 경우에도 결제내역과 플레이어 정보가 보존됩니다.\n" +
                " 소셜 로그인으로 생성된 계정 정보와 게스트 로그인으로 생성된 계정 정보는 서로 다른 계정이므로 데이터가 서로 공유되지 않습니다.\n\n" +
                "주의 사항\n" +
                " 게스트 로그인의 경우 비밀번호 분실 및 타인에게 노출을 주의해주세요.";
            Agree = "동의";
            GoogleLogin = "구글 플레이 로그인";
            GameCenterLogin = "게임 센터 로그인";
            GuestLogin = "게스트 로그인";

            access_level[0] = "비밀글";
            access_level[1] = "친구 공개";
            access_level[2] = "전체 공개";
        }
        else
        {
            LOGIN_network = "Please, check your internet connection";
            LOGIN_version = "Please, update your app version";
            LOGIN_otherwork = "Realtime game disconnected because you paused";
            LOGOLOGIN_networkerror = "Sorry for Networking Error";
            LOGOLOGIN_networktimeover = "Too long server waiting time";
            LOGIN_WarningNicknameContains = "Nickname can't contains @ and blank";
            LOGIN_WarningNickname = "Please type 2~8 letters for nickname";
            LOGIN_WarningEmailLength = "Please type 8~30 letters for E-mail";
            LOGIN_WarningEmail = "Please type E-mail with correct form";
            LOGIN_WarningEmailAlready = "E-mail address Already exists";
            LOGIN_WarningNicknameAlready = "Nickname Already exists";
            LOGIN_WarningUnknown = "Sorry for Unknown error";
            LOGIN_WarningDatabase = "Sorry for Database error";
            LOGIN_WarningServerError = "Sorry for Server error";
            LOGIN_WarningNoNick = "There is no account";
            LOGIN_WarningWrongPin = "Can't verify account";
            LOGIN_FailSocialLogin = "Fail to social login";
            LOGIN_WaitingForToken = "Waiting for token";
            LOGIN_CheckVersion = "Please, update game to new version";
            LOGIN_NicknameDuple = "Duplicate nickname";
            LOGIN_LoginDuple = "Login from another device";
            LOGIN_LoginFail = "Login failed";
            LOGIN_LoginExpiredFail = "Login info is expired, Please restart the game";
            LOGIN_NicknameEmpty = "Nickname is blank";
            LOGIN_IDPWEmpty = "ID or Password is blank";
            LOGIN_InvalidNickname = "Nickname can not contain @,/,\\,\" and blank";
            LOGIN_InvalidID = "ID can not contain special characters and blank";
            LOGIN_InvalidPW = "Password can not contain /,\\{0} 만큼 동전을 던지시겠습니까?,\" and blank";
            LOGIN_NotLogined = "You're not logined";
            LOGIN_Block = "You're blocked until {0}";
            LOGIN_DiffPwMessage = "ID you typed is already exist or password is wrong";
            MAINGAME_NickPopupMessage = "Please input your nickname";
            MAINGAME_WarningVerrify = "Can't verify account";
            MAINGAME_FriendListFail = "Fail to get the friend list";
            MAINGAME_GoingSquare = "Would you like to go to the square?";
            MAINGAME_VisitMessage = "Would you like to request to visit {0}'s house?";
            MAINGAME_VisitantMessage = "There is a visit request from {0}";
            MAINGAME_GoingHome = "Would you like to go home?";
            MAINGAME_MasterLeave = "You returned home because the owner left";
            MAINGAME_GuestBusy = "Guest is not available for visit";
            MAINGAME_BuyingMessage = "Would you like to buy in {0} gem?";
            MAINGAME_SuccessToBuy = "Purchase succeeded";
            MAINGAME_NotEnoughGem = "There is not enough gem";
            MAINGAME_PutFurnitureMessage = "Would you like to put it in the room?";
            MAINGAME_BlockMessage = "Do you want to block this user?";
            MAINGAME_UnblockMessage = "Do you want to unblock this user?";
            MAINGAME_FriendLimitMessage = "You can not make friends anymore";
            MAINGAME_FriendAddMessage = "Would you like to request a friend?";
            MAINGAME_FriendRemoveMessage = "Are you sure you want to delete this friend?";
            MAINGAME_FashionshowEnterMessage = "Would you like to participate in a fashion show after ads?";
            MAINGAME_FashionshowWaitMessage = "There are {0} minutes {1} seconds left until the next fashion show";
            MAINGAME_FashionshowRemainMessage = "There are {0} people waiting for a fashion show";
            MAINGAME_FashionshowCancelMessage = "Would you like to cancel your participation in the fashion show?";
            MAINGAME_FashionshowScoreLimitMessage = "The score can range from 50 to 100 points";
            MAINGAME_FashionshowScoreMessage = "{1} people rated it and {0} got {2} points";
            MAINGAME_FashionshowScore0Message = "0 people rated it and {0} got {1} points by random score";
            MAINGAME_FashionshowDisabled = "Fashionshow option is disabled";
            MAINGAME_yes = "Yes";
            MAINGAME_no = "No";
            MAINGAME_confirm = "Confirm";
            MAINGAME_WrongOccured = "Wrong request";
            MAINGAME_NickScoreMessage = "Would you like to know marital compatibility?";
            MAINGAME_NickScoreListMessage = "Choose a user";
            MAINGAME_ProfileEditMessage = "Please input a profile message";
            MAINGAME_FountainCoinThrowingMessage = "Would you like to throw {0} coins?";
			MAINGAME_FountainCoinThrownMessage = "You've thrown {0} coins";
			MAINGAME_FountainLessCashMessage = "You don't have enough gems";
			MAINGAME_FountainInvalidCoinMessage = "You can't throw coins with that amount";
            MSG_FriendRequestMessage = "Friend request message came from {0}";
            MSG_FriendAcceptMessage = "{0} accepted a friend request from {1}";
            MSG_FriendRefuseMessage = "{0} refused a friend request from {1}";
            MSG_FriendDeleteMessage = "{0} deleted {1} from {0}'s friends";
            MSG_FriendRequestSended = "You sended a friend request message to {0}";
            MSG_FriendRequestReceived = "You received a friend request message from {0}";
            MSG_VisitRequestMessage = "{0} requested a visit";
            MSG_FriendDupleMessage = "This user is already friend";
            MSG_FriendFailToRequestMessage = "Failed to send a friend request message";
            MSG_FriendFailToAcceptMessage = "Failed to accept a friend";
            MSG_FailToWatchMessage = "Failed to watching ads";
            MSG_Quit = "Do you want to quit?";
            MSG_Update = "We will check server for a moment soon";
            MSG_MsgAccepted = "You've got the message from {0}";
            MSG_UnlockSlotMessage = "Would you like to buy a slot {0} for {1} gems?";
            MSG_SaveSlotMessage = "Do you save your clothes at slot {0}?";
            MSG_LoadSlotMessage = "Do you load clothes from slot {0}?";
            MSG_ExitChatMessage = "Do you want to exit this chat room?";
            MSG_DiaryBlockMessage = "You've been blocked from diary owner";
            MSG_DiaryNotFriendMessage = "You're not friend with diary owner";
            MSG_DiaryAddMessage = "Do you want to add a post?";
            MSG_DiaryEditMessage = "Do you want to edit the post?";
            MSG_DiarDeleteMessage = "Do you want to delete the post?";
            MSG_DiaryAddReplyMessage = "Do you want to add a reply?";
            MSG_DiaryEditReplyMessage = "Do you want to edit the post?";
            MSG_DiaryDeleteReplyMessage = "Do you want to delete the post?";
            MSG_DiaryEmptyMessage = "Title or content is empty";
            MSG_AdoptRaiseMessage = "Would you like to raise this status with {0} gems?";
			MSG_AdoptDeleteMessage = "Would you like to delete this adopt slot?";
            MAINGAME_NoUserMessage = "This user has been signed out";
            MINIGAME_exitMessage = "Would you like to leave the room?";
            MINIGAME_scoreMessage = "You got the gems for {0}";
            MINIGAME_PartnerLeave = "{0} has left";
            MINIGAME_DiceGameEnterMessage = "Do you want to start a dice game?";
            MINIGAME_FootholdGameEnterMessage = "Do you want to start a foothold game?";
            MAINGAME_FootholdGameRuleMessage = "Please select one of the 4 footholds during the time limit\nAfter selecting the correct foothold, you will get some gems";
            MINIGAME_BlindDateEnterMessage = "Would you like to go to a blind date?";
            MINIGAME_FailToScoreMessage = "You could not get gems";
            MAINGAME_ChChangeMessage = "Do you want to change channel?";
            MAINGAME_GoSlotMessage = "Would you like to go to the slot room?";
            MAINGAME_FishingGameEnterMessage = "Would you like to go to the fishing cafe?";
            MAINGAME_GoPianoMessage = "Would you like to go to the piano room?";
            MAINGAME_HangmanGameEnterMessage = "Do you want to start a hangman game?";
			MAINGAME_HangmanGameRuleMessage = "Click on the alphabet to correct the word\nGet gems every time the alphabet is right.\nAt the end of the game, the most-hit users will be given additional gems!";
			MINIGAME_RunningEnterMessage = "Would you like to go to the running room?";
			MINIGAME_RunningBettingMessage = "Do you want to bet?";
			MINIGAME_RunningGameRuleMessage = "Please bet on 1 of the 6 characters.\nIf you bet on the winner, you will get gems as dividend rate x10. You can cheer your betting character to be faster. You can't cheer if your character hasn't stamina enough.";
            SHOP_msg1 = "Welcome to the shop~";
            SHOP_msg2 = "Please look around";
            SHOP_RandomClothMessage = "Would you like to buy {1} random cloth boxes with {0} gems?";
            SHOP_RandomFurnitureMessage = "Would you like to buy {1} random furniture box with {0} gems?";
            SHOP_GemMessage = "Would you like to purchase total {0} gems?";
            SHOP_GemEarnedMessage = "Your gem is now {0}";
            SHOP_DupleReceipt = "This receipt is duplicated";
            SHOP_FailToReceipt = "Fail to purchase";
            SHOP_InvalidReceipt = "This receipt is invalid";
            SHOP_FullItemMessage = "You have all items";
            SHOP_LessItemMessage = "The number of missing items is less than the number of items you intend to buy";
            SHOP_HaveItemMessage = "This item is already purchased";
            SHOP_SlotMessage = "Add Slot {0}";
            OPTION_FashionshowView = "Seeing the fashion show";
            OPTION_Report = "Report";
            OPTION_ReportSuccessMessage = "Success to report";
            OPTION_ReportLimitMessage = "You've exhausted 10 report chances today";
            OPTION_BGM = "BGM";
            OPTION_SE = "SE";
            OPTION_Speak = "Speech";
            OPTION_friendRequest = "Enable friend request";
            OPTION_visitRequest = "Enable visit request";
            Rule = "Rule";
            Gem = "Gem";
            Random = "Random";
            Cloth = "Cloth";
            Furniture = "Furniture";
            DiceGame = "Dice Game";
            FootholdGame = "Foothold Game";
            FishingCafe = "Fishing Cafe";
            PianoRoom = "Piano Room";
			HangmanGame = "Hangman Game";
            Diary = "Diary";
            GuestBook = "Guest Book";
            Write = "Write";
            Reply = "Reply";
            Edit = "Edit";
            Delete = "Delete";
            Cancel = "Cancel";
            Confirm = "Confirm";
            Accept = "Accept";
            Refuse = "Refuse";
            Result = "Result";
            Report = "Report";
            UserList = "User List";
            Relationship = "Relationship";
            Post = "Post";
            Item = "Item";
            Box = "Box";
            Waiting = "Waiting";
            Option = "Option";
            Slot = "Slot";
            Save = "Save";
            Load = "Load";
			Fountain = "Fountain";
			Rank = "Rank";
			CoinThrowing = "Coin Throwing";
			Stamina = "Stamina";
			Running = "Running";
			Speed = "Speed";
			Record = "Record";
			Adopt = "Adopt";
			Betting = "Betting";
			Sec = "sec";
            PrivacyTerms = "FamilSoft respect users privacy so take it very carefully.\n" +
                "For users privacy, FamilSoft keep several rules.\n" +

                "1)FamilSoft seek consent for player to collect users information.\n" +
                "2)Only minimal information for playing.\n" +
                "3)FamilSoft manages users information safty.\n\n" +
                "Which information FamilSoft collect?\n" +
                " 1)Account ID and 2)In game purchase in Fortune's closet.\n" +
                " Purchase list and player data will preservate even reinstall the game.\n" +
                " social login account and guest login account is different account so 2 account never share the player data.\n\n" +
                "Precautions\n" +
                " Case guest login, be careful for forget of password and don't tell it to other person.";
            Agree = "Agree";
            GoogleLogin = "Google Play Login";
            GameCenterLogin = "Game Center Login";
            GuestLogin = "Guest Login";

            access_level[0] = "Secret";
            access_level[1] = "Friend only";
            access_level[2] = "Full disclosure";
        }

        isInitailized = true;
    }
}
